
export const TABLE_ROWS = [
    {
        item_name: "Mozzarella Sticks",
        category: "Appetizers",
        category_color: "yellow",
        options_available: ["Regular", "Large"],
        amount_in_stock: "0",
        price: "7.99",
        cost: 3.5,
    },
    {
        item_name: "Chicken Wings",
        category: "Appetizers",
        category_color: "yellow",
        options_available: ["Mild", "Medium", "Hot"],
        amount_in_stock: "75",
        price: "10.99",
        cost: 5.0,
    },
    {
        item_name: "Burger",
        category: "Main Course",
        category_color: "green",
        options_available: ["Single", "Double", "Triple"],
        amount_in_stock: "50",
        price: "12.99",
        cost: 6.0,
    },
    {
        item_name: "Burger",
        category: "Main Course",
        category_color: "green",
        options_available: ["Single", "Double", "Triple"],
        amount_in_stock: "60",
        price: "12.99",
        cost: 6.0,
    },
    {
        item_name: "French Fries",
        category: "Sides",
        category_color: "blue",
        options_available: ["Regular", "Large"],
        amount_in_stock: "100",
        price: "3.99",
        cost: 1.5,
    },
];